#ifndef ERRORS_H
#define ERRORS_H

enum Error {
	OK,
	ERR_NULL_PTR,
	ERR_INVALID_INPUT,
	ERR_UNKNOWN,
	ERR_PARSE_FEN_PIECES,
	ERR_PARSE_FEN_COLOR,
	ERR_PARSE_FEN_CASTLING,
	ERR_PARSE_FEN_EP,
	ERR_PARSE_FEN_HALF_MOVE,
	ERR_PARSE_FEN_MOVE,
};
typedef enum Error Error;

#endif
